# Generated by Django 3.2.4 on 2021-06-27 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beitrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('gueltig', models.BooleanField()),
                ('beitrag', models.DecimalField(decimal_places=2, max_digits=8)),
                ('versicherung1', models.DecimalField(decimal_places=2, max_digits=8)),
                ('versicherung2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('versicherung3', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Beitraggruppen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppe', models.CharField(max_length=40)),
                ('faktor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Beitragsgruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppenname', models.CharField(max_length=40)),
                ('beitrag', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Buchungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buchungstext', models.CharField(max_length=100)),
                ('buchungsdatum', models.DateField()),
                ('konto', models.CharField(max_length=5)),
                ('sollhaben', models.CharField(max_length=1)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gegenkonto', models.CharField(max_length=5)),
                ('einnahmeausgabe', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Flugmodelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modellname', models.CharField(max_length=40)),
                ('modelltyp', models.CharField(max_length=40)),
                ('antrieb', models.CharField(max_length=40)),
                ('spannweite', models.IntegerField(max_length=5)),
                ('gewicht', models.IntegerField(max_length=6)),
                ('motortyp', models.CharField(max_length=40)),
                ('hubraum', models.IntegerField(max_length=5)),
                ('luftschraube', models.CharField(max_length=40)),
                ('material', models.CharField(max_length=40)),
                ('schalldaempfer', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Funktionen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funktion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mitglieder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField(max_length=6)),
                ('anrede', models.CharField(max_length=10)),
                ('vorname', models.CharField(max_length=40)),
                ('nachname', models.CharField(max_length=40)),
                ('strasse', models.CharField(max_length=40)),
                ('plz', models.CharField(max_length=5)),
                ('ort', models.CharField(max_length=40)),
                ('telefon', models.CharField(max_length=40)),
                ('mobiltel', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('werbung', models.BooleanField()),
                ('geburtstag', models.DateField()),
                ('geb_anzeigen', models.BooleanField()),
                ('austritt', models.DateField()),
                ('gestorben', models.DateField()),
                ('beitrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('versicherungsbeitrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iban', models.CharField(max_length=22)),
                ('bic', models.CharField(max_length=12)),
                ('foto', models.FilePathField(max_length=255)),
                ('kenntnisnachweisnr', models.CharField(max_length=20)),
                ('kenntnisnachweisdatum', models.DateField()),
                ('kenntnisnachweisgueltig', models.BooleanField()),
                ('dmfvnummer', models.CharField(max_length=20)),
                ('beitragsgruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.beitragsgruppe')),
                ('funktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.funktionen')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=40)),
                ('vorname', models.CharField(max_length=40)),
                ('alias', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('frage1', models.CharField(max_length=100)),
                ('rechte', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Verein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vereinsname', models.CharField(max_length=40)),
                ('strasse', models.CharField(max_length=40)),
                ('postfach', models.CharField(max_length=20)),
                ('plz', models.CharField(max_length=5)),
                ('ort', models.CharField(max_length=40)),
                ('telefon', models.CharField(max_length=20)),
                ('internet', models.URLField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('datum_gruendung', models.DateField()),
                ('vereinsregisternr', models.CharField(max_length=20)),
                ('registergericht', models.CharField(max_length=40)),
                ('finanzamt', models.CharField(max_length=40)),
                ('iban1', models.CharField(max_length=22)),
                ('bic1', models.CharField(max_length=12)),
                ('bank1', models.CharField(max_length=40)),
                ('iban2', models.CharField(max_length=22)),
                ('bic2', models.CharField(max_length=12)),
                ('bank2', models.CharField(max_length=40)),
                ('logo_dateiname', models.FilePathField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vorstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_von', models.DateField()),
                ('datum_bis', models.DateField()),
                ('funktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.funktionen')),
                ('mitgliednummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mitglieder')),
            ],
        ),
        migrations.CreateModel(
            name='Laermpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messort', models.CharField(max_length=40)),
                ('messdatum', models.DateTimeField()),
                ('messbeauftragter', models.CharField(max_length=40)),
                ('niederschlag', models.BooleanField()),
                ('windgeschwindigkeit', models.DecimalField(decimal_places=1, max_digits=6)),
                ('temperatur', models.DecimalField(decimal_places=1, max_digits=5)),
                ('schallmessgeraet', models.CharField(max_length=40)),
                ('windmessgeraet', models.CharField(max_length=40)),
                ('thermometer', models.CharField(max_length=40)),
                ('flugmodellnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flugmodelle')),
            ],
        ),
        migrations.AddField(
            model_name='flugmodelle',
            name='mitgliednummer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mitglieder'),
        ),
        migrations.CreateModel(
            name='Dokumente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(max_length=40)),
                ('dokumentname', models.CharField(max_length=100)),
                ('dateiname', models.FilePathField(max_length=255)),
                ('mitgliednummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mitglieder')),
            ],
        ),
    ]
