# Generated by Django 3.2.4 on 2021-07-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beitrag',
            name='versicherung1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beitrag',
            name='versicherung2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beitrag',
            name='versicherung3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='dokumente',
            name='dateiname',
            field=models.FilePathField(max_length=254, path='../documents'),
        ),
        migrations.AlterField(
            model_name='mitglieder',
            name='austritt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mitglieder',
            name='bic',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mitglieder',
            name='dmfvnummer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mitglieder',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mitglieder',
            name='foto',
            field=models.FilePathField(blank=True, max_length=254, null=True, path='../images'),
        ),
        migrations.AlterField(
            model_name='mitglieder',
            name='geburtstag',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mitglieder',
            name='gestorben',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mitglieder',
            name='iban',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='mitglieder',
            name='kenntnisnachweisdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mitglieder',
            name='kenntnisnachweisnr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mitglieder',
            name='mobiltel',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='mitglieder',
            name='telefon',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='frage1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='verein',
            name='bank2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='verein',
            name='bic2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='verein',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='verein',
            name='iban2',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='verein',
            name='logo_dateiname',
            field=models.FilePathField(blank=True, max_length=254, null=True, path='../images'),
        ),
        migrations.AlterField(
            model_name='verein',
            name='postfach',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='verein',
            name='strasse',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vorstand',
            name='datum_bis',
            field=models.DateField(blank=True, null=True),
        ),
    ]
